-- phpMyAdmin SQL Dump
--
-- Datenbank: `typo3_test`
--

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `tx_sfjquery_scripts`
--

CREATE TABLE `tx_sfjquery_scripts` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(11) NOT NULL DEFAULT '0',
  `tstamp` int(11) NOT NULL DEFAULT '0',
  `crdate` int(11) NOT NULL DEFAULT '0',
  `cruser_id` int(11) NOT NULL DEFAULT '0',
  `deleted` tinyint(4) NOT NULL DEFAULT '0',
  `hidden` tinyint(4) NOT NULL DEFAULT '0',
  `name` tinytext,
  `domscript` text,
  `domscriptfile` tinytext,
  `outscript` text,
  `outscriptfile` tinytext,
  `content` text,
  `htmlfile` tinytext,
  `ts` text,
  `tsfile` tinytext,
  `cssuifile` tinytext,
  `css` text,
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Daten für Tabelle `tx_sfjquery_scripts`
--

INSERT INTO `tx_sfjquery_scripts` (`uid`, `pid`, `name`, `domscript`, `domscriptfile`, `outscript`, `outscriptfile`, `content`, `htmlfile`, `ts`, `tsfile`, `cssuifile`, `css`) VALUES (1, 0, 'Example: Alert', 'alert(''Hello world'');', '', '', '', '', '', '', '', '', '');
INSERT INTO `tx_sfjquery_scripts` (`uid`, `pid`, `name`, `domscript`, `domscriptfile`, `outscript`, `outscriptfile`, `content`, `htmlfile`, `ts`, `tsfile`, `cssuifile`, `css`) VALUES (2, 0, 'Example: FunctionCall', 'coolFunction(''Hello world'');', '', 'function coolFunction(text) {\r\n	alert(text);\r\n}', '', '', '', '', '', '', '');
INSERT INTO `tx_sfjquery_scripts` (`uid`, `pid`, `name`, `domscript`, `domscriptfile`, `outscript`, `outscriptfile`, `content`, `htmlfile`, `ts`, `tsfile`, `cssuifile`, `css`) VALUES (3, 0, 'Example: Dragable', '$("#draggable").draggable();\r\n', '', '', '', '<div id="draggable" class="ui-widget-content">\r\n	<p>Drag me around</p>\r\n</div>\r\n', '', '', '', 'typo3conf/ext/sfjquery/res/dark-hive/jquery-ui-1.7.2.custom.css', '#draggable { width: 150px; height: 150px; padding: 0.5em; }\r\n');
INSERT INTO `tx_sfjquery_scripts` (`uid`, `pid`, `name`, `domscript`, `domscriptfile`, `outscript`, `outscriptfile`, `content`, `htmlfile`, `ts`, `tsfile`, `cssuifile`, `css`) VALUES (4, 0, 'Example: Dropable', '$("#draggable").draggable();\r\n$("#droppable").droppable({\r\n	drop: function(event, ui) {\r\n		$(this).addClass(''ui-state-highlight'').find(''p'').html(''Dropped!'');\r\n	}\r\n});', '', '', '', '<div id="draggable" class="ui-widget-content">\r\n	<p>Drag me to my target</p>\r\n</div>\r\n\r\n<div id="droppable" class="ui-widget-header">\r\n	<p>Drop here</p>\r\n</div>\r\n', '', '', '', 'typo3conf/ext/sfjquery/res/dark-hive/jquery-ui-1.7.2.custom.css', '#draggable { width: 100px; height: 100px; padding: 0.5em; float: left; margin: 10px 10px 10px 0; }\r\n	#droppable { width: 150px; height: 150px; padding: 0.5em; float: left; margin: 10px; }\r\n	');
INSERT INTO `tx_sfjquery_scripts` (`uid`, `pid`, `name`, `domscript`, `domscriptfile`, `outscript`, `outscriptfile`, `content`, `htmlfile`, `ts`, `tsfile`, `cssuifile`, `css`) VALUES (5, 0, 'Example: Resizeable', '$("#resizable").resizable();\r\n', '', '', '', '<div id="resizable" class="ui-widget-content">\r\n	<h3 class="ui-widget-header">Resizable</h3>\r\n</div>\r\n', '', '', '', 'typo3conf/ext/sfjquery/res/dark-hive/jquery-ui-1.7.2.custom.css', '#resizable { width: 150px; height: 150px; padding: 0.5em; }\r\n	#resizable h3 { text-align: center; margin: 0; }\r\n	');
INSERT INTO `tx_sfjquery_scripts` (`uid`, `pid`, `name`, `domscript`, `domscriptfile`, `outscript`, `outscriptfile`, `content`, `htmlfile`, `ts`, `tsfile`, `cssuifile`, `css`) VALUES (6, 0, 'Example: Selectable', '$("#selectable").selectable();\r\n', '', '', '', '<ol id="selectable">\r\n	<li class="ui-widget-content">Item 1</li>\r\n	<li class="ui-widget-content">Item 2</li>\r\n	<li class="ui-widget-content">Item 3</li>\r\n	<li class="ui-widget-content">Item 4</li>\r\n	<li class="ui-widget-content">Item 5</li>\r\n	<li class="ui-widget-content">Item 6</li>\r\n	<li class="ui-widget-content">Item 7</li>\r\n</ol>\r\n', '', '', '', 'typo3conf/ext/sfjquery/res/dark-hive/jquery-ui-1.7.2.custom.css', '#feedback { font-size: 1.4em; }\r\n#selectable .ui-selecting { background: #FECA40; }\r\n#selectable .ui-selected { background: #F39814; color: white; }\r\n#selectable { list-style-type: none; margin: 0; padding: 0; width: 60%; }\r\n#selectable li { margin: 3px; padding: 0.4em; font-size: 1.4em; height: 18px; }\r\n	');
INSERT INTO `tx_sfjquery_scripts` (`uid`, `pid`, `name`, `domscript`, `domscriptfile`, `outscript`, `outscriptfile`, `content`, `htmlfile`, `ts`, `tsfile`, `cssuifile`, `css`) VALUES (7, 0, 'Example: Sortable', '$("#sortable").sortable();\r\n$("#sortable").disableSelection();\r\n', '', '', '', '<ul id="sortable">\r\n	<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>Item 1</li>\r\n	<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>Item 2</li>\r\n	<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>Item 3</li>\r\n	<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>Item 4</li>\r\n	<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>Item 5</li>\r\n	<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>Item 6</li>\r\n	<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>Item 7</li>\r\n</ul>', '', '', '', 'typo3conf/ext/sfjquery/res/dark-hive/jquery-ui-1.7.2.custom.css', '#sortable { list-style-type: none; margin: 0; padding: 0; width: 60%; }\r\n#sortable li { margin: 0 3px 3px 3px; padding: 0.4em; padding-left: 1.5em; font-size: 1.4em; height: 18px; }\r\n#sortable li span { position: absolute; margin-left: -1.3em; }');
INSERT INTO `tx_sfjquery_scripts` (`uid`, `pid`, `name`, `domscript`, `domscriptfile`, `outscript`, `outscriptfile`, `content`, `htmlfile`, `ts`, `tsfile`, `cssuifile`, `css`) VALUES (8, 0, 'Example: Accordion', '$("#accordion").accordion();\r\n', '', '', '', '<div id="accordion">\r\n	<h3><a href="#">Section 1</a></h3>\r\n	<div>\r\n		<p>\r\n		Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer\r\n		ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit\r\n		amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut\r\n		odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.\r\n		</p>\r\n	</div>\r\n	<h3><a href="#">Section 2</a></h3>\r\n	<div>\r\n		<p>\r\n		Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet\r\n		purus. Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttitor\r\n		velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In\r\n		suscipit faucibus urna.\r\n		</p>\r\n	</div>\r\n	<h3><a href="#">Section 3</a></h3>\r\n	<div>\r\n		<p>\r\n		Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis.\r\n		Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero\r\n		ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis\r\n		lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui.\r\n		</p>\r\n		<ul>\r\n			<li>List item one</li>\r\n			<li>List item two</li>\r\n			<li>List item three</li>\r\n		</ul>\r\n	</div>\r\n	<h3><a href="#">Section 4</a></h3>\r\n	<div>\r\n		<p>\r\n		Cras dictum. Pellentesque habitant morbi tristique senectus et netus\r\n		et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in\r\n		faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia\r\n		mauris vel est.\r\n		</p>\r\n		<p>\r\n		Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus.\r\n		Class aptent taciti sociosqu ad litora torquent per conubia nostra, per\r\n		inceptos himenaeos.\r\n		</p>\r\n	</div>\r\n</div>\r\n', '', '', '', 'typo3conf/ext/sfjquery/res/dark-hive/jquery-ui-1.7.2.custom.css', '');
INSERT INTO `tx_sfjquery_scripts` (`uid`, `pid`, `name`, `domscript`, `domscriptfile`, `outscript`, `outscriptfile`, `content`, `htmlfile`, `ts`, `tsfile`, `cssuifile`, `css`) VALUES (9, 0, 'Example: Datepicker', '$("#datepicker").datepicker();\r\n', '', '', '', '<p>Date: <input id="datepicker" type="text"></p>\r\n', '', '', '', 'typo3conf/ext/sfjquery/res/dark-hive/jquery-ui-1.7.2.custom.css', '');
INSERT INTO `tx_sfjquery_scripts` (`uid`, `pid`, `name`, `domscript`, `domscriptfile`, `outscript`, `outscriptfile`, `content`, `htmlfile`, `ts`, `tsfile`, `cssuifile`, `css`) VALUES (10, 0, 'Example: Dialog', '$.ui.dialog.defaults.bgiframe = true;\r\n$(function() {\r\n	$("#dialog").dialog();\r\n});\r\n', '', '', '', '<div id="dialog" title="Basic dialog">\r\n	<p>This is the default dialog which is useful for displaying information. The dialog window can be moved, resized and closed with the ''x'' icon.</p>\r\n</div>\r\n', '', '', '', 'typo3conf/ext/sfjquery/res/dark-hive/jquery-ui-1.7.2.custom.css', '');
INSERT INTO `tx_sfjquery_scripts` (`uid`, `pid`, `name`, `domscript`, `domscriptfile`, `outscript`, `outscriptfile`, `content`, `htmlfile`, `ts`, `tsfile`, `cssuifile`, `css`) VALUES (11, 0, 'Example: Progressbar', '$("#progressbar").progressbar({\r\n	value: 37\r\n});\r\n', '', '', '', '<div id="progressbar"></div>\r\n', '', '', '', 'typo3conf/ext/sfjquery/res/dark-hive/jquery-ui-1.7.2.custom.css', '');
INSERT INTO `tx_sfjquery_scripts` (`uid`, `pid`, `name`, `domscript`, `domscriptfile`, `outscript`, `outscriptfile`, `content`, `htmlfile`, `ts`, `tsfile`, `cssuifile`, `css`) VALUES (12, 0, 'Example: Slider', '$("#slider-range-max").slider({\r\n	range: "max",\r\n	min: 1,\r\n	max: 10,\r\n	value: 2,\r\n	slide: function(event, ui) {\r\n		$("#amount").val(ui.value);\r\n	}\r\n});\r\n$("#amount").val($("#slider-range-max").slider("value"));\r\n', '', '', '', '<p>\r\n<labe for="amount">Minimum number of bedrooms:</label>\r\n<input type="text" id="amount" style="border:0; color:#f6931f; font-weight:bold;" />\r\n</p>\r\n<div id="slider-range-max"></div>\r\n', '', '', '', 'typo3conf/ext/sfjquery/res/dark-hive/jquery-ui-1.7.2.custom.css', '#demo-frame > div.demo { padding: 10px !important; };\r\n');
INSERT INTO `tx_sfjquery_scripts` (`uid`, `pid`, `name`, `domscript`, `domscriptfile`, `outscript`, `outscriptfile`, `content`, `htmlfile`, `ts`, `tsfile`, `cssuifile`, `css`) VALUES (13, 0, 'Example: Tabs', '$("#tabs").tabs();\r\n', '', '', '', '<div id="tabs">\r\n	<ul>\r\n		<li><a href="#tabs-1">Nunc tincidunt</a></li>\r\n		<li><a href="#tabs-2">Proin dolor</a></li>\r\n		<li><a href="#tabs-3">Aenean lacinia</a></li>\r\n	</ul>\r\n	<div id="tabs-1">\r\n		<p>Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus. Curabitur nec arcu. Donec sollicitudin mi sit amet mauris. Nam elementum quam ullamcorper ante. Etiam aliquet massa et lorem. Mauris dapibus lacus auctor risus. Aenean tempor ullamcorper leo. Vivamus sed magna quis ligula eleifend adipiscing. Duis orci. Aliquam sodales tortor vitae ipsum. Aliquam nulla. Duis aliquam molestie erat. Ut et mauris vel pede varius sollicitudin. Sed ut dolor nec orci tincidunt interdum. Phasellus ipsum. Nunc tristique tempus lectus.</p>\r\n	</div>\r\n	<div id="tabs-2">\r\n		<p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante, ut pharetra massa metus id nunc. Duis scelerisque molestie turpis. Sed fringilla, massa eget luctus malesuada, metus eros molestie lectus, ut tempus eros massa ut dolor. Aenean aliquet fringilla sem. Suspendisse sed ligula in ligula suscipit aliquam. Praesent in eros vestibulum mi adipiscing adipiscing. Morbi facilisis. Curabitur ornare consequat nunc. Aenean vel metus. Ut posuere viverra nulla. Aliquam erat volutpat. Pellentesque convallis. Maecenas feugiat, tellus pellentesque pretium posuere, felis lorem euismod felis, eu ornare leo nisi vel felis. Mauris consectetur tortor et purus.</p>\r\n	</div>\r\n	<div id="tabs-3">\r\n		<p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce sodales. Quisque eu urna vel enim commodo pellentesque. Praesent eu risus hendrerit ligula tempus pretium. Curabitur lorem enim, pretium nec, feugiat nec, luctus a, lacus.</p>\r\n		<p>Duis cursus. Maecenas ligula eros, blandit nec, pharetra at, semper at, magna. Nullam ac lacus. Nulla facilisi. Praesent viverra justo vitae neque. Praesent blandit adipiscing velit. Suspendisse potenti. Donec mattis, pede vel pharetra blandit, magna ligula faucibus eros, id euismod lacus dolor eget odio. Nam scelerisque. Donec non libero sed nulla mattis commodo. Ut sagittis. Donec nisi lectus, feugiat porttitor, tempor ac, tempor vitae, pede. Aenean vehicula velit eu tellus interdum rutrum. Maecenas commodo. Pellentesque nec elit. Fusce in lacus. Vivamus a libero vitae lectus hendrerit hendrerit.</p>\r\n	</div>\r\n</div>\r\n', '', '', '', 'typo3conf/ext/sfjquery/res/dark-hive/jquery-ui-1.7.2.custom.css', '');
